version: "3.9"

services:
  dev-db:
    image: postgres:17
    container_name: nest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db1234
      POSTGRES_DB: nest
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data: